### ISSUE TITLE
Subject Inference: allow choosing a less restricted optional path 

### ISSUE THREAD

**Issue by binh-vu** [binh-vu/drepr-v2#4]
Consider the following example:

```yaml
attributes:
  deposit_type_name: ["MineralSite", .., ["deposit_type_candidate"], .., ["observed_name"]]
  deposit_type_source: ["MineralSite", .., ["deposit_type_candidate"], .., "source"]
  deposit_type_confidence: ["MineralSite", .., ["deposit_type_candidate"], .., ["confidence"]]
  deposit_type_normalized_uri: ["MineralSite", .., ["deposit_type_candidate"], .., ["normalized_uri"]]
semantic_model:
  mndr:DepositTypeCandidate:1:
    properties:
      - [mndr:observed_name, deposit_type_name]
      - [mndr:source, deposit_type_source]
      - [mndr:normalized_uri, deposit_type_normalized_uri, drepr:uri]
      - [mndr:confidence, deposit_type_confidence]
```

We should be able to just pick `deposit_type_source` because it will always have one-to-one to the rest of the attributes (the other way around is not)
